# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcbd0d0fdebc89178eef2cfc5850e3c35608cac8bf5328d6c3b9b6b798820f3e48401c52b46fff6ddd97319e9ddf18ac3b9706a1c35cd24e9e0154188f244a4a

test:
  secret_key_base: cd7fceb050e8f02591faecfc9ea3bacfcc726eaf09ad1b0775a37a35274641f6e676f9c47bbc64bd6f36de49fdc75f68a470db76ef2ed354a9672707ef31abfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
